{% set data = load_setup_py_data() %}

package:
  name: openalea.root_bridges
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: {{PYTHON}} setup.py install #--single-version-externally-managed --record=record.txt

requirements:
  build:
    - python {{PY_VER}}
    - setuptools
    - openalea.deploy
  run:
    - python >=3.8
    # Model
    - openalea.mtg
    - pandas
    - numpy
    - dataclasses

test:
  requires:
    - pytest
  imports:
    - rhizodep
    - root_cynaps
    - data_utility
    - genericmodel
  source_files:
    - test/**
  commands:
    - cd test
    - pytest -v --ignore=test_aml.py  --ignore=test_stat.py

about:
  home: {{ data.get('url') }}
  license: CeCILL-C
  summary: {{ data.get('description') }}
